apiVersion: apps/v1
kind: Deployment
metadata:
  name: famous-quotes
  namespace: avalon
  labels:
    app: famous-quotes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: famous-quotes
  template:
    metadata:
      labels:
        app: famous-quotes
    spec:
      containers:
      - name: quotes
        image: quay.io/redhattraining/famous-quotes:1.0
