apiVersion: "v1"
kind: "LimitRange"
metadata:
  name: "avalon-constraints"
spec:
  limits:
    - type: "Pod"
      max:
        cpu: "500m"
        memory: "500Mi"
      min:
        cpu: "100m"
        memory: "100Mi"
    - type: "Container"
      max:
        cpu: "300m"
        memory: "300Mi"
      min:
        cpu: "50m"
        memory: "50Mi"
      defaultRequest:
        cpu: "150m"
        memory: "150Mi"
