apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster
spec:
  identityProviders:
  - name: github
    challenge: false
    login: true
    mappingMethod: claim 
    type: GitHub
    github:
      clientID: e1766cdfa9830007d3ba
      clientSecret:
        name: githubsecret 
