apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      description: Exposes and load balances the application pods
    labels:
      app: web
      template: httpd-example
    name: frontend
  spec:
    ports:
    - name: web
      port: 8080
      targetPort: 8080
    selector:
      name: frontend
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    labels:
      app: web
      template: httpd-example
    name: frontend
  spec:
    host: ""
    to:
      kind: Service
      name: frontend
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    annotations:
      description: Keeps track of changes in the application image
    labels:
      app: web
      template: httpd-example
    name: frontend
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    annotations:
      description: Defines how to build the application
      template.alpha.openshift.io/wait-for-ready: "true"
    labels:
      app: web
      template: httpd-example
    name: frontend
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: frontend:latest
    source:
      contextDir: ""
      git:
        ref: ""
        uri: https://github.com/sclorg/httpd-ex.git
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: httpd:2.4-el8
          namespace: openshift
      type: Source
    triggers:
    - type: ImageChange
    - type: ConfigChange
    - github:
        secret: cGs7HvSqbVMfF8eB7vcp6QpaobOHqKIJ2owSmMJv
      type: GitHub
    - generic:
        secret: s5QGbHXixyu3P4LVXu5nrWvJo1nM22vihM7mjAyh
      type: Generic
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    annotations:
      description: Defines how to deploy the application server
      template.alpha.openshift.io/wait-for-ready: "true"
    labels:
      app: web
      template: httpd-example
    name: frontend
  spec:
    replicas: 1
    selector:
      name: frontend
    strategy:
      type: Rolling
    template:
      metadata:
        labels:
          name: frontend
        name: frontend
      spec:
        containers:
        - env: []
          image: ' '
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 30
            timeoutSeconds: 3
          name: httpd-example
          ports:
          - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 3
            timeoutSeconds: 3
          resources:
            limits:
              memory: 512Mi
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - httpd-example
        from:
          kind: ImageStreamTag
          name: frontend:latest
      type: ImageChange
    - type: ConfigChange
kind: List
metadata: {}
