apiVersion: batch/v1
kind: Job
metadata:
  name: my-job
spec:
  template:
    spec:
      containers:
      - name: my-job-container
        image: my-job-image
        command: ["./run-task.sh"]
      restartPolicy: Never
  backoffLimit: 4
