apiVersion: v1
kind: LimitRange
metadata:
  name: demo-limit-range
spec:
  limits:
  - default:
      cpu: 500m
      memory: 512Mi
    defaultRequest:
      cpu: 100m
      memory: 256Mi
    max:
      cpu: 1
      memory: 1Gi
    min:
      cpu: 50m
      memory: 128Mi
    type: Container
