apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: bridge-net
spec:
  config: '{
    "cniVersion": "0.3.1",
    "type": "bridge",
    "bridge": "mybridge",
    "isGateway": true,
    "ipam": {
      "type": "host-local",
      "subnet": "192.168.2.0/24",
      "routes": [
        {
          "dst": "0.0.0.0/0"
        }
      ]
    }
  }'
