apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-specific
  namespace: backend
spec:
  podSelector:
    matchLabels:
      type: secured
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          type: source
    - podSelector:
        matchLabels:
          type: allowed
