apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  annotations:
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"config.openshift.io/v1","kind":"OAuth","metadata":{"annotations":{"include.release.openshift.io/ibm-cloud-managed":"true","include.release.openshift.io/self-managed-high-availability":"true","include.release.openshift.io/single-node-developer":"true","release.openshift.io/create-only":"true"},"creationTimestamp":"2024-05-06T09:08:29Z","generation":2,"name":"cluster","ownerReferences":[{"apiVersion":"config.openshift.io/v1","kind":"ClusterVersion","name":"version","uid":"f9ceddcf-8f39-4050-8406-4846a617adae"}],"resourceVersion":"30193","uid":"0f424889-a5a9-4bbd-a352-49504153366f"},"spec":{"identityProviders":[{"htpasswd":{"fileData":{"name":"ex280-htpass-secret"}},"mappingMethod":"claim","name":"local-users","type":"HTPasswd"}],"templates":{"login":{"name":"login-template"}},"tokenConfig":{"accessTokenMaxAgeSeconds":0}}}
    release.openshift.io/create-only: "true"
  creationTimestamp: "2024-05-06T09:08:29Z"
  generation: 4
  name: cluster
  ownerReferences:
  - apiVersion: config.openshift.io/v1
    kind: ClusterVersion
    name: version
    uid: f9ceddcf-8f39-4050-8406-4846a617adae
  resourceVersion: "48046"
  uid: 0f424889-a5a9-4bbd-a352-49504153366f
spec:
  identityProviders:
  - htpasswd:
      fileData:
        name: ex280-htpass-secret
    mappingMethod: claim
    name: local-users
    type: HTPasswd
  templates:
    login:
      name: login-template
  tokenConfig:
    accessTokenMaxAgeSeconds: 0
